#!/usr/bin/env python3
"""
LevvDeck netlist generator.

This is the SINGLE SOURCE OF TRUTH for the LevvDeck board topology. It emits a
KiCad-compatible netlist (``levvdeck.net``) that downstream tools consume
(``kinet2pcb`` -> ``levvdeck.kicad_pcb``). The same data block is imported by:

  - scripts/gen_bom.py          (BOM)
  - scripts/gen_u1_footprint.py (custom ESP32 DevKitC socket footprint)
  - gen_connections.py          (levvdeck-connections.md)

The ESP32 GPIO assignments here MUST stay identical to the ``#define`` block in
``firmware.ino``. Do not change a pin in one place without the other.

Usage:
    python3 gen_netlist.py            # writes levvdeck.net
    python3 gen_netlist.py --check    # validate counts, print summary, exit
    python3 gen_netlist.py -o out.net # custom output path

No third-party dependencies; pure standard library so it runs anywhere.
"""

from __future__ import annotations

import argparse
import sys
from collections import OrderedDict

# ---------------------------------------------------------------------------
# LOCKED PINOUT  (mirror of firmware.ino — keep in sync)
# ---------------------------------------------------------------------------
# Maps a logical function to the ESP32 GPIO label as silkscreened on a
# DevKitC-V4 (e.g. "IO21"). These labels are also the pad names of the custom
# U1 socket footprint, so the netlist node pin == footprint pad name.
PINOUT = OrderedDict([
    ("I2C_SDA",  "IO21"),
    ("I2C_SCL",  "IO22"),
    ("ROW0",     "IO13"),
    ("ROW1",     "IO14"),
    ("ROW2",     "IO27"),
    ("COL0",     "IO26"),
    ("COL1",     "IO25"),
    ("COL2",     "IO33"),
    ("ENC1_A",   "IO16"),
    ("ENC1_B",   "IO17"),
    ("ENC1_SW",  "IO4"),
    ("ENC2_A",   "IO32"),
    ("ENC2_B",   "IO18"),
    ("ENC2_SW",  "IO19"),
    ("WS2812",   "IO23"),
])

# ---------------------------------------------------------------------------
# FOOTPRINTS  (verified against KiCad 8/9 standard libraries)
# ---------------------------------------------------------------------------
FP = {
    "SW":   "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB",
    "D":    "Diode_THT:D_DO-35_SOD27_P7.62mm_Horizontal",       # pad1 = cathode
    "RV":   "Rotary_Encoder:RotaryEncoder_Alps_EC11E-Switch_Vertical_H20mm",
    "J":    "Connector_PinHeader_2.54mm:PinHeader_1x04_P2.54mm_Vertical",
    "R":    "Resistor_THT:R_Axial_DIN0207_L6.3mm_D2.5mm_P10.16mm_Horizontal",
    # NOTE: brief said LED_WS2812B_PLCC4_5.0x5.0mm_P1.6mm, which does not exist
    # in the KiCad lib (that pitch is the 6-pin PLCC6 part). The correct 4-pin
    # WS2812B 5050 footprint is P3.2mm.
    "LED":  "LED_SMD:LED_WS2812B_PLCC4_5.0x5.0mm_P3.2mm",
    # Custom socket footprint generated by scripts/gen_u1_footprint.py into the
    # project-local LevvDeck.pretty library.
    "U1":   "LevvDeck:ESP32_DevKitC_38P_Socket",
}

# Canonical DevKitC-V4 38-pin layout (single source of truth; also imported by
# scripts/gen_u1_footprint.py). Top->bottom, viewed from the top with USB down.
U1_LEFT_LABELS = [
    "3V3", "EN", "IO36", "IO39", "IO34", "IO35", "IO32", "IO33", "IO25",
    "IO26", "IO27", "IO14", "IO12", "GND", "IO13", "IO9", "IO10", "IO11", "5V",
]
U1_RIGHT_LABELS = [
    "GND", "IO23", "IO22", "IO1", "IO3", "IO21", "GND", "IO19", "IO18", "IO5",
    "IO17", "IO16", "IO4", "IO0", "IO2", "IO15", "IO8", "IO7", "IO6",
]

# Electrical pad names per part (verified against the KiCad libraries). Used to
# declare every pad in the netlist so KiCad's "Update PCB from Netlist" imports
# with no "no pin X in symbol" warnings. Empty-named mechanical pads (e.g. the
# Cherry MX NPTH mounting holes) are intentionally omitted — KiCad ignores them.
PART_PADS = {
    "SW":  ["1", "2"],
    "D":   ["1", "2"],
    "RV":  ["A", "B", "C", "S1", "S2", "MP"],
    "J":   ["1", "2", "3", "4"],
    "R":   ["1", "2"],
    "LED": ["1", "2", "3", "4"],
    # unique-preserving order for the 38 DevKitC pads (GND appears 3x -> 1 name)
    "U1":  list(dict.fromkeys(U1_LEFT_LABELS + U1_RIGHT_LABELS)),
}

# 3x3 matrix, COL2ROW. Each entry: (switch, diode, row_net, col_net)
MATRIX = [
    ("SW1", "D1", "ROW0", "COL0"),
    ("SW2", "D2", "ROW0", "COL1"),
    ("SW3", "D3", "ROW0", "COL2"),
    ("SW4", "D4", "ROW1", "COL0"),
    ("SW5", "D5", "ROW1", "COL1"),
    ("SW6", "D6", "ROW1", "COL2"),
    ("SW7", "D7", "ROW2", "COL0"),
    ("SW8", "D8", "ROW2", "COL1"),
    ("SW9", "D9", "ROW2", "COL2"),
]

# Number of WS2812 LEDs in the chain (locked to 2 per design decision).
NUM_WS2812 = 2


def build_design():
    """Return (components, nets).

    components: list of dict(ref, value, footprint, desc)
    nets:       OrderedDict(net_name -> list of (ref, pad))
    """
    components = []
    nets = OrderedDict()

    def add(ref, pad, net):
        nets.setdefault(net, []).append((ref, pad))

    # --- U1: ESP32 DevKitC socket -----------------------------------------
    components.append(dict(ref="U1", value="ESP32-DevKitC",
                           footprint=FP["U1"],
                           desc="ESP32-WROOM-32 dev board, socketed (B.Cu)"))
    add("U1", "3V3", "+3V3")
    add("U1", "5V",  "+5V")
    add("U1", "GND", "GND")          # U1 has 3 pads named GND, all on net GND
    for func, gpio in PINOUT.items():
        if func == "WS2812":
            add("U1", gpio, "WS_DRIVE")        # IO23 -> R1
        elif func.startswith("I2C_"):
            add("U1", gpio, func)              # I2C_SDA / I2C_SCL
        else:
            add("U1", gpio, func)              # ROWn/COLn/ENCx_* nets

    # --- Switch matrix + diodes (COL2ROW) ---------------------------------
    for sw, d, row, col in MATRIX:
        internal = "n_%s_%s" % (sw, d)        # SWx.pad2 <-> Dx anode (pad2)
        components.append(dict(ref=sw, value="MX", footprint=FP["SW"],
                               desc="Cherry MX 1u keyswitch"))
        components.append(dict(ref=d, value="1N4148", footprint=FP["D"],
                               desc="Matrix diode (pad1=cathode)"))
        add(sw, "1", col)                     # SWx.pad1 -> COLn
        add(sw, "2", internal)                # SWx.pad2 -> Dx anode
        add(d, "2", internal)                 # Dx anode (pad2)
        add(d, "1", row)                      # Dx cathode (pad1) -> ROWn

    # --- Rotary encoders (EC11 with push switch) --------------------------
    # Pads: A,B = quadrature; C = common -> GND; S1,S2 = switch; MP = mounting.
    for ref, a_net, b_net, sw_net in (
        ("RV1", "ENC1_A", "ENC1_B", "ENC1_SW"),
        ("RV2", "ENC2_A", "ENC2_B", "ENC2_SW"),
    ):
        components.append(dict(ref=ref, value="EC11", footprint=FP["RV"],
                               desc="Alps EC11 rotary encoder w/ switch"))
        add(ref, "A", a_net)
        add(ref, "B", b_net)
        add(ref, "C", "GND")
        add(ref, "S1", sw_net)
        add(ref, "S2", "GND")
        add(ref, "MP", "GND")                 # mounting pins tied to GND

    # --- OLED header J1 (1x4) ---------------------------------------------
    # Default silk order GND/VCC/SCL/SDA — VERIFY against your module (HUMAN CHECK).
    components.append(dict(ref="J1", value="OLED_I2C", footprint=FP["J"],
                           desc="0.96in SSD1306 OLED header (GND/VCC/SCL/SDA)"))
    add("J1", "1", "GND")
    add("J1", "2", "+3V3")
    add("J1", "3", "I2C_SCL")
    add("J1", "4", "I2C_SDA")

    # --- WS2812 data resistor R1 ------------------------------------------
    components.append(dict(ref="R1", value="330", footprint=FP["R"],
                           desc="WS2812 data series resistor"))
    add("R1", "1", "WS_DRIVE")                # from IO23
    add("R1", "2", "WS_DIN1")                 # to LED1 DIN

    # --- WS2812 chain ------------------------------------------------------
    # Pad map: 1=VDD(+5V), 2=DOUT, 3=VSS(GND), 4=DIN.
    prev_din_net = "WS_DIN1"
    for i in range(1, NUM_WS2812 + 1):
        ref = "LED%d" % i
        components.append(dict(ref=ref, value="WS2812B", footprint=FP["LED"],
                               desc="WS2812B addressable RGB LED"))
        add(ref, "1", "+5V")
        add(ref, "3", "GND")
        add(ref, "4", prev_din_net)           # DIN
        if i < NUM_WS2812:
            chain = "WS_CHAIN%d" % i
            add(ref, "2", chain)              # DOUT -> next DIN
            prev_din_net = chain
        # last LED DOUT (pad2) intentionally left unconnected

    # --- declare every remaining footprint pad ----------------------------
    # KiCad warns ("no pin X in symbol") for any footprint pad missing from the
    # netlist. Put each still-floating pad on its own unconnected-() net, which
    # is exactly how KiCad's own netlists represent no-connects.
    fp_pads = {FP[kind]: pads for kind, pads in PART_PADS.items()}
    present = {(ref, pad) for nodes in nets.values() for (ref, pad) in nodes}
    for c in components:
        for pad in fp_pads.get(c["footprint"], []):
            if (c["ref"], pad) not in present:
                nets["unconnected-(%s-%s)" % (c["ref"], pad)] = [(c["ref"], pad)]

    return components, nets


# ---------------------------------------------------------------------------
# KiCad netlist (.net) emitter
# ---------------------------------------------------------------------------
def _esc(s: str) -> str:
    return str(s).replace('"', r'\"')


def render_netlist(components, nets) -> str:
    out = []
    out.append('(export (version "E")')
    out.append('  (design')
    out.append('    (source "gen_netlist.py")')
    out.append('    (date "generated")')
    out.append('    (tool "LevvDeck gen_netlist.py"))')

    # components
    out.append('  (components')
    for c in components:
        out.append('    (comp (ref "%s")' % _esc(c["ref"]))
        out.append('      (value "%s")' % _esc(c["value"]))
        out.append('      (footprint "%s")' % _esc(c["footprint"]))
        out.append('      (description "%s"))' % _esc(c["desc"]))
    out.append('  )')

    # nets
    out.append('  (nets')
    for code, (name, nodes) in enumerate(nets.items(), start=1):
        out.append('    (net (code "%d") (name "%s")' % (code, _esc(name)))
        for ref, pad in nodes:
            out.append('      (node (ref "%s") (pin "%s"))' % (_esc(ref), _esc(pad)))
        out.append('    )')
    out.append('  )')
    out.append(')')
    return "\n".join(out) + "\n"


def summarize(components, nets):
    n_comp = len(components)
    n_unconn = sum(1 for name in nets if name.startswith("unconnected-"))
    n_signal = len(nets) - n_unconn
    # An unresolved footprint = empty/None footprint string.
    unresolved = [c["ref"] for c in components if not c.get("footprint")]
    return n_comp, n_signal, n_unconn, unresolved


def main(argv=None):
    p = argparse.ArgumentParser(description="Generate LevvDeck KiCad netlist")
    p.add_argument("-o", "--output", default="levvdeck.net",
                   help="output netlist path (default: levvdeck.net)")
    p.add_argument("--check", action="store_true",
                   help="validate and print summary; do not write")
    args = p.parse_args(argv)

    components, nets = build_design()
    n_comp, n_signal, n_unconn, unresolved = summarize(components, nets)

    print("LevvDeck design summary")
    print("  footprints (components): %d  (expected 25 for 2x WS2812)" % n_comp)
    print("  signal nets:             %d  (this topology = 29)" % n_signal)
    print("  unconnected stub nets:   %d  (floating pads, incl. spare U1 GPIO)"
          % n_unconn)
    print("  total nets:              %d" % (n_signal + n_unconn))
    print("  unresolved footprints:   %d" % len(unresolved))
    if unresolved:
        print("    -> " + ", ".join(unresolved))

    expected_comp = 25 if NUM_WS2812 == 2 else 24
    problems = []
    if n_comp != expected_comp:
        problems.append("component count %d != expected %d" % (n_comp, expected_comp))
    if n_signal != 29:
        problems.append("signal net count %d != expected 29" % n_signal)
    if unresolved:
        problems.append("unresolved footprints present")

    if args.check:
        if problems:
            print("\nFAIL:")
            for pr in problems:
                print("  - " + pr)
            return 1
        print("\nOK: 25 footprints, 29 signal nets, all pads declared.")
        print("Every footprint pad is in a net, so KiCad's netlist import is\n"
              "clean (no 'no pin X in symbol' warnings).")
        return 0

    text = render_netlist(components, nets)
    with open(args.output, "w") as fh:
        fh.write(text)
    print("\nWrote %s" % args.output)
    if problems:
        print("WARNING:")
        for pr in problems:
            print("  - " + pr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
