#!/usr/bin/env python3
"""
Regenerate levvdeck-connections.md (the human-readable connection reference)
from the shared design data block. Run after any pinout/topology change.

Usage: python3 gen_connections.py [-o levvdeck-connections.md]
"""

from __future__ import annotations

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_netlist import build_design, PINOUT, FP, NUM_WS2812  # noqa: E402
from scripts.gen_u1_footprint import (  # noqa: E402
    LEFT_LABELS, RIGHT_LABELS, label_to_net, PADS_PER_ROW,
)


def _refkey(ref):
    m = re.match(r"([A-Za-z]+)(\d+)", ref)
    return (m.group(1), int(m.group(2))) if m else (ref, 0)


def render():
    components, nets = build_design()
    out = []
    out.append("# LevvDeck — Connections & Footprints\n")
    out.append("> Auto-generated by `gen_connections.py` from the shared data "
               "block in `gen_netlist.py`. Do not edit by hand — edit the data "
               "block and regenerate. The ESP32 pinout here is identical to the "
               "`#define`s in `firmware.ino`.\n")

    out.append("## ESP32 pinout (locked)\n")
    out.append("| Function | GPIO |")
    out.append("|---|---|")
    out.append("| I2C SDA | %s |" % PINOUT["I2C_SDA"])
    out.append("| I2C SCL | %s |" % PINOUT["I2C_SCL"])
    out.append("| Matrix ROW0/1/2 | %s / %s / %s |" %
               (PINOUT["ROW0"], PINOUT["ROW1"], PINOUT["ROW2"]))
    out.append("| Matrix COL0/1/2 | %s / %s / %s |" %
               (PINOUT["COL0"], PINOUT["COL1"], PINOUT["COL2"]))
    out.append("| Encoder1 A/B/SW | %s / %s / %s |" %
               (PINOUT["ENC1_A"], PINOUT["ENC1_B"], PINOUT["ENC1_SW"]))
    out.append("| Encoder2 A/B/SW | %s / %s / %s |" %
               (PINOUT["ENC2_A"], PINOUT["ENC2_B"], PINOUT["ENC2_SW"]))
    out.append("| WS2812 DATA | %s (via R1) |" % PINOUT["WS2812"])
    out.append("| Power | 3V3->OLED VCC, 5V(VIN)->WS2812 VDD, GND common |\n")

    out.append("## Components / footprints (%d total)\n" % len(components))
    out.append("| Ref | Value | Footprint |")
    out.append("|---|---|---|")
    for c in sorted(components, key=lambda c: _refkey(c["ref"])):
        out.append("| %s | %s | `%s` |" % (c["ref"], c["value"], c["footprint"]))
    out.append("")

    out.append("## Matrix (3x3, COL2ROW)\n")
    out.append("Per key: `SWx.pad1 -> COLn`, `SWx.pad2 -> Dx anode (pad2)`, "
               "`Dx cathode (pad1) -> ROWn`.\n")
    out.append("```")
    out.append("        COL0      COL1      COL2")
    out.append("ROW0    SW1/D1    SW2/D2    SW3/D3")
    out.append("ROW1    SW4/D4    SW5/D5    SW6/D6")
    out.append("ROW2    SW7/D7    SW8/D8    SW9/D9")
    out.append("```\n")

    signal = [(n, nd) for n, nd in nets.items()
              if not n.startswith("unconnected-")]
    n_unconn = len(nets) - len(signal)
    out.append("## Nets (%d signal)\n" % len(signal))
    out.append("| # | Net | Nodes (ref.pad) |")
    out.append("|---|---|---|")
    for i, (name, nodes) in enumerate(signal, 1):
        node_s = ", ".join("%s.%s" % (r, p) for r, p in nodes)
        out.append("| %d | `%s` | %s |" % (i, name, node_s))
    out.append("")
    out.append("_Plus %d `unconnected-(...)` stub nets — one per floating "
               "footprint pad (spare U1 GPIO + LED2 DOUT) — so KiCad's netlist "
               "import is warning-free._\n" % n_unconn)

    out.append("## U1 — ESP32 DevKitC socket pad map\n")
    out.append("> 🛑 **HUMAN CHECK**: row spacing must be measured with "
               "calipers; verify this pad order matches YOUR DevKit silk. "
               "Footprint `%s`.\n" % FP["U1"])
    net_of = label_to_net()
    out.append("| Pin | Left label | Net | Pin | Right label | Net |")
    out.append("|---|---|---|---|---|---|")
    for i in range(PADS_PER_ROW):
        ll, rl = LEFT_LABELS[i], RIGHT_LABELS[i]
        out.append("| %d | %s | %s | %d | %s | %s |" %
                   (i + 1, ll, net_of[ll] or "—",
                    i + 20, rl, net_of[rl] or "—"))
    out.append("")

    out.append("## 🛑 HUMAN CHECK items before fabrication\n")
    out.append("1. **Diode polarity** — `Dx.pad1` is the **cathode** and must "
               "face the ROW net. (Footprint `%s`, pad1=K.)" % FP["D"])
    out.append("2. **OLED header J1 order** — default is GND/VCC/SCL/SDA "
               "(pins 1-4). Confirm against your module's silk; VCC/GND or "
               "SCL/SDA order may differ.")
    out.append("3. **EC11 pads** — A/B = quadrature, C = common to GND, "
               "S1/S2 = push switch. Confirm against the module.")
    out.append("4. **U1 row spacing + USB edge** — measured spacing, pad "
               "mapping, and USB-to-edge cutout all correct.\n")
    out.append("_WS2812 count: %d._\n" % NUM_WS2812)
    return "\n".join(out)


def main(argv=None):
    p = argparse.ArgumentParser(description="Generate connections markdown")
    p.add_argument("-o", "--output", default="levvdeck-connections.md")
    args = p.parse_args(argv)
    with open(args.output, "w") as fh:
        fh.write(render() + "\n")
    print("Wrote %s" % args.output)
    return 0


if __name__ == "__main__":
    sys.exit(main())
